version: '3.8'

services:
  backend:
    build: ./todo_backend
    ports:
      - "5000:5000"
    networks:
      - todo-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/Todo
    depends_on:
      - mongo

  frontend:
    build: ./todo_frontend
    ports:
      - "80:80"
    networks:
      - todo-network
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
